### PR TITLE
api: change byte-count type from uint32_t to size_t

### PR DESCRIPTION
**Pull request by alfredh**
it is quite common to use `size_t'.

ref: http://stackoverflow.com/questions/994288/size-t-vs-int-in-c-and-or-c

### CODE REVIEW

**Comment by twittner** [comment]
I'd prefer explicitly sized integral types.

**Comment by romanb** [comment]
The choice of `uint32_t` was indeed intentional. I think the reasoning was that it does not seem practical to encrypt or decrypt payloads larger than `uint32_t` in an API that is neither streaming / incremental nor in-place. Thus `uint32_t` seemed like like the more explicit and minimally more efficient choice, for both 32bit and 64bit architectures. Does that make sense or do you nevertheless see good reasons to prefer `size_t`?

**Comment by twittner** [comment]
Although I agree that `size_t` is more idiomatic C/C++ when it comes to indexing or size. I guess I am neutral regarding this change.

**Comment by romanb** [comment]
My pendulum has swung towards favouring `size_t` and I will thus merge the PR. If anyone has second thoughts don't hesitate to raise them. Thanks @alfredh!

**Pull request merged**
